#!/usr/bin/env python3
"""DOX guard — flag boundaries whose source changed without a matching AGENTS.md update.

A *boundary* is any directory containing an `AGENTS.md` (its DOX contract). For each
changed file we find its nearest owning boundary; if a boundary's source changed but
its `AGENTS.md` did not, we flag it — a reminder to run the DOX "update after editing"
pass (see the root AGENTS.md). This does NOT judge whether a doc update was *needed*;
DOX allows "no behavior/contract change" edits — it just surfaces the decision.

Usage:
  dox_check.py --staged             # files staged for commit (the pre-commit hook uses this)
  dox_check.py --base origin/main   # everything changed vs a ref (CI)
  dox_check.py --files a.py b.py     # an explicit list
  dox_check.py ... --strict         # exit 1 on findings (CI); default warns + exits 0

No third-party deps; stdlib only.
"""
from __future__ import annotations

import argparse
import fnmatch
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOC = "AGENTS.md"

# Paths that never count as "source under a boundary" (generated / data / vendored).
IGNORE = [
    ".git/*", "*/__pycache__/*", "*.pyc", ".venv/*", "*/.venv/*",
    "*.egg-info/*", "app/*/.build/*", "*/DerivedData/*",
    "*.xcodeproj/*",            # generated by XcodeGen
    "data/*",                   # the DB + corpora, not code
    "*/node_modules/*", "*.lock", "*.png", "*.jpg", "*.jpeg",
    "AGENTS.md", "*/AGENTS.md",  # the docs themselves are tracked separately below
]


def _git(*args: str) -> list[str]:
    out = subprocess.run(["git", *args], cwd=REPO_ROOT,
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.stderr.write(out.stderr)
        sys.exit(2)
    return [l for l in out.stdout.splitlines() if l.strip()]


def changed_files(args: argparse.Namespace) -> list[str]:
    if args.files:
        return args.files
    if args.staged:
        return _git("diff", "--cached", "--name-only", "--diff-filter=ACMR")
    if args.base:
        return _git("diff", "--name-only", "--diff-filter=ACMR", f"{args.base}...HEAD")
    sys.stderr.write("dox_check: pass --staged, --base <ref>, or --files <...>\n")
    sys.exit(2)


def boundaries() -> set[Path]:
    """Every directory (relative to repo root) that owns an AGENTS.md."""
    return {p.parent.relative_to(REPO_ROOT) for p in REPO_ROOT.rglob(DOC)
            if not _ignored(str(p.relative_to(REPO_ROOT)))}


def _ignored(rel: str) -> bool:
    # AGENTS.md is matched by the IGNORE list but we WANT it for doc detection,
    # so this helper is used only for source files; docs are detected by name.
    return any(fnmatch.fnmatch(rel, pat) for pat in IGNORE) and not rel.endswith(DOC)


def nearest_boundary(rel: str, bset: set[Path]) -> Path | None:
    d = Path(rel).parent
    while True:
        if d in bset:
            return d
        if d == Path("."):
            return Path(".") if Path(".") in bset else None
        d = d.parent


def main() -> int:
    ap = argparse.ArgumentParser(description="DOX doc-drift guard")
    ap.add_argument("--staged", action="store_true")
    ap.add_argument("--base", help="git ref to diff against (CI)")
    ap.add_argument("--files", nargs="*", help="explicit file list")
    ap.add_argument("--strict", action="store_true", help="exit 1 on findings")
    args = ap.parse_args()

    bset = boundaries()
    files = [f for f in changed_files(args)]

    docs_touched: set[Path] = set()      # boundaries whose AGENTS.md changed
    src_touched: dict[Path, list[str]] = {}  # boundary -> changed source files

    for f in files:
        if f.endswith(DOC):
            docs_touched.add(Path(f).parent)
            continue
        if _ignored(f):
            continue
        b = nearest_boundary(f, bset)
        if b is not None:
            src_touched.setdefault(b, []).append(f)

    flagged = {b: fs for b, fs in src_touched.items() if b not in docs_touched}

    if not flagged:
        print("DOX guard: OK — every changed boundary had its AGENTS.md reviewed.")
        return 0

    print("DOX guard: source changed under these boundaries without an AGENTS.md update:\n")
    for b in sorted(flagged, key=str):
        doc = (b / DOC) if str(b) != "." else Path(DOC)
        print(f"  ▸ {doc}")
        for f in sorted(flagged[b]):
            print(f"      - {f}")
    print("\nRun the DOX 'update after editing' pass: review the listed AGENTS.md")
    print("and update it (or confirm no contract changed). See the root AGENTS.md.")
    return 1 if args.strict else 0


if __name__ == "__main__":
    raise SystemExit(main())
